[package]
name = "sterling-harness"
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
sterling-kernel = { path = "../kernel" }
serde_json = "1"
hex = "0.4"

[dev-dependencies]
tempfile = "3"
